# Generated by Django 5.0.1 on 2024-02-02 06:48

import customer.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_user_is_verified_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', customer.manager.UserManager()),
            ],
        ),
    ]
