# Generated by Django 5.0.1 on 2024-01-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_tags_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='The Best Category.', null=True),
        ),
    ]
