# Generated by Django 5.0.1 on 2024-01-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendor_date_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='mall',
            field=models.CharField(default='مرکز خرید', max_length=100),
        ),
    ]
