# Generated by Django 5.0.1 on 2024-02-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='user',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.product'),
        ),
    ]
