# Generated by Django 5.0.3 on 2024-03-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_wishlist_product_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
